### ISSUE TITLE
Does not handle response status code 401

### ISSUE THREAD

**Issue by janeeisenstein** [genericclient/genericclient-requests#13]
When a user sends a GET request to a DRF server using invalid base authentication email/password values, a response status code of 401 is returned. The client does not raise an exception when this happens, which results in a None resource being returned. The client should raise NotAuthenticatedError for both 401 and 403 status codes. See https://www.django-rest-framework.org/api-guide/authentication/

**Comment by janeeisenstein** [comment]
@fcurella Please let me know when you release a version that includes this fix.

**Comment by fcurella** [comment]
@janeeisenstein will do. It's taking quite a bit because Travis-CI is being slow in starting new builds

**Comment by fcurella** [comment]
@janeeisenstein I've just released v1.4.2
